### ISSUE TITLE
Allowing more advanced filters

### ISSUE THREAD

**Issue by canvural** [thomasjsn/laravel-scout-elastic#10]
Hi,

I have a proposal. But its a kinda hacky way :smile: In the Laravel Scout documentation it says where clauses are only used for basic numeric equality checks. But in ElasticSearch we can do more.

Currently the `filters` method in the `ElasticsearchEngine` only uses `term` for filtering. But we can change this method to be more flexible. A really quick implementation i tried is: 

```php
protected function filters(Builder $builder)
{
    return collect($builder->wheres)->map(function ($value, $key) {
        return [$key => [key($value) => current($value)]];
    })->values()->all();
}
```

So this will allow us to write queries like this:

```php
\App\SomeModel::elasticSearch('multi_match', 'some_query', [
    'fields' => ['title', 'content', 'tags'],
    'fuzziness' => 'auto',
    'prefix_length' => 2,
    'operator' => 'AND'
])->where('range', [
    'created_at' => [
        'gte' => '2017-05-16 00:00:00',
        'lte' => '2017-05-20 00:00:00'
    ]
])->get()
```

What are your thoughts about this?

**Comment by thomasjsn** [comment]
I am all for expanding the filtering. We could use the traditional approach if the filtering value is not an array.

**Comment by canvural** [comment]
Ok, cool. I will try to prepare some PR somewhere next week.

**Comment by thomasjsn** [comment]
Remember to include tests.
