### ISSUE TITLE
Missing ElasticSearchable

### ISSUE THREAD

**Issue by ajayfroiden** [thomasjsn/laravel-scout-elastic#11]
I could not find the ElasticSearchable class.

**Comment by thomasjsn** [comment]
You need 
```
use ScoutEngines\Elasticsearch\ElasticSearchable;
```
at the top, then to use this trait in the class.

**Comment by ajayfroiden** [comment]
It is not recognising.
http://prntscr.com/g2vur2

Is the Laravel version issue. I am using laravel 5.4

**Comment by thomasjsn** [comment]
It's not a Laravel issue, I am also using 5.4. If that class can not be found, then the package is probably not installed correctly. Since this does not have it's own packagist.org package it must be installed using the `repositories` option in composer.json.

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/thomasjsn/laravel-scout-elastic"
    }
  ],
...
"tamayo/laravel-scout-elastic": "dev-master",
```

**Comment by ajayfroiden** [comment]
Yes you are right. The one that  i used using composer require has not all the files.
Could you please add it to packagist.

Is there any feature by which we can sort the results by location. I have data with latitude and longitude stored to the database

**Comment by thomasjsn** [comment]
I've added it to packagist.org, use `thomasjsn/laravel-scout-elastic`

There is no feature to sort by location, you will have to use the underlying ElasticSearch php library directly for that.

**Comment by ajayfroiden** [comment]
Other that elastic search php library is there any laravel package that i can use for distance filtering

**Comment by thomasjsn** [comment]
Maybe this one? https://github.com/basemkhirat/elasticsearch
