### ISSUE TITLE
How I can install it via composer? Problem with minimum-stability even in dev:

### ISSUE THREAD

**Issue by igarbera** [thomasjsn/laravel-scout-elastic#7]
Could not find package thomasjsn/laravel-scout-elastic at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability

**Comment by thomasjsn** [comment]
Yeah, it's not on Packagist. Either you need to manually download or clone it. Or you could keep the `ErickTamayo/laravel-scout-elastic` package in your `composer.json` and also add the following:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/thomasjsn/laravel-scout-elastic"
    }
  ],
```

I might put it on Packagist, haven't quite decided.

**Comment by igarbera** [comment]
I try this way but not success. But after fork I add to composer.json repository type Package: 

```
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "igarbera/laravel-scout-elastic",
                "version": "3.0.2",
                "autoload": { "psr-0": { "igarbera\\laravel-scout-elastic": "" } },
                "source": {
                    "url": "https://github.com/igarbera/laravel-scout-elastic.git",
                    "type": "git",
                    "reference": "tags/3.0.2"
                }
            }
        }
    ]

```
After it its installed (tag 3.0.2  =  your master branch). Then I add  Trait to model: 

```
<?php

namespace App\Models;
use ScoutEngines\Elasticsearch\ElasticSearchable;
use Illuminate\Database\Eloquent\Model;


class Page extends Model
{
    use ElasticSearchable;
    public $timestamps = true;
    protected $fillable = ['slug','title','text','mp3','image','status'];
}

```
But have another problem.... 
```
FatalErrorException in Page.php line 10:
Trait 'ScoutEngines\Elasticsearch\ElasticSearchable' not found
```

Can You help with it? I need fuzzy search very much but I want to use it pretty nice, via/as Laravel Scout .

**Comment by thomasjsn** [comment]
If `ScoutEngines\Elasticsearch\ElasticSearchable` doesn't exist then it isn't installed correctly.

**Comment by zvermafia** [comment]
@thomasjsn could you explain how to install correctly, I also tried to install your package (fork) via composer but unsuccessful...

I did like below:
Added `repository` section to the `composer.json`:
```
// ...
"type": "project",
"repositories": [
    { "type": "vcs", "url": "https://github.com/thomasjsn/laravel-scout-elastic" }
],
"require": {
// ...
```
Then executed `composer update`, the composer didn't output any error. But if I try to search, laravel outputs `Trait 'ScoutEngines\Elasticsearch\ElasticSearchable' not found'...
