### ISSUE TITLE
Ordering not doing anything

### ISSUE THREAD

**Issue by reinierkors** [thomasjsn/laravel-scout-elastic#8]
Hi, I'm trying to use the following:
```
$videos = Video::elasticSearch('multi_match', $query, [
	            'fields' => ['title', 'description', 'labels'],
	            'fuzziness' => 'auto',
	            'prefix_length' => 1,
	            'operator' => 'AND'
	        ])->orderBy('publishedAt', 'desc') 
                  ->paginate(5);
```
But the results I'm getting are not ordered by publishedAt date. I'm getting the same data, with or without the orderBy:

Example entry:
```
{
    "id": 1,
    "title": "Title",
    "description": "Description",
    "publishedAt": "2017-01-24 00:00:00"
}
```

Do you know what the problem could be?

**Comment by VRuzhentsov** [comment]
Because _score sorting is in priority
I am fixed it in this way
https://github.com/VRuzhentsov/laravel-scout-elastic/commit/761a2c5e6dc35142cb22435ce31d47544b802ea2

in  `src/ElasticsearchEngine.php:176` swap position in array_merge() function

**Comment by thomasjsn** [comment]
@VRuzhentsov is right, in my repo `_score` has priority. So only when the score is identical will the ordering be used.

**Comment by VRuzhentsov** [comment]
@thomasjsn  do you want, that I implement settings for `_score` priority? (as branch to yours last commit, without my other improvement proposals )

**Comment by VRuzhentsov** [comment]
@reinierkors alternatively, you can try to add `boost` param in query, to set `_score` identical, and maybe in this case, ordering begin to work
