### ISSUE TITLE
Why where clause doesn't work on production?

### ISSUE THREAD

**Issue by zvermafia** [thomasjsn/laravel-scout-elastic#9]
On local machine where clause works fine, but on production doesn't work. It means if I add where clause to elasticSearch() method it gives nothing for result:
```php
// Fine
Model::elasticSearch('multi_match', 'some query')->get();
// Fail on production, but on local fine
Model::elasticSearch('multi_match', 'some query')->where('status', 1)->get();
```
What could be the reason?

P.S. There are data with 3 different status values: 1, 0, -1

**Comment by thomasjsn** [comment]
Are there any differences in ElasticSearch version?

**Comment by zvermafia** [comment]
Local VM (homestead 1.0.1) / Elasticsearch (curl -XGET 'localhost:9200' outputs):
```json
{
  "name" : "Vargas",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "lya-lya-lya", // edited
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "c849dd13904f53e63e88efc33b2ceeda0b6a1276",
    "build_timestamp" : "2017-04-24T16:18:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```
Production (provisioned via forge) / Elasticsearch (curl -XGET 'localhost:9200' outputs):
```json
{
  "name" : "Foggy Nelson",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "lya-lya-lya", // edited
  "version" : {
    "number" : "2.4.5",
    "build_hash" : "c849dd13904f53e63e88efc33b2ceeda0b6a1276",
    "build_timestamp" : "2017-04-24T16:18:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```

On both machines I use this [script](http://forgerecipes.com/recipes/73) to install ElasticSearch

**Comment by thomasjsn** [comment]
Sorry; I don't know what is causing this for you. And I don't have any knowledge with forge. But it is not a problem with the package (as far as I know).

**Comment by zvermafia** [comment]
Forge is [forge.laravel.com](http://forge.laravel.com)

**Comment by thomasjsn** [comment]
Yeah I know what forge is, I just don't know much about it. I would make sure that the database structure is the same, and that the data indexed in elastic search is the same. Apart from that; not sure I'm much help.
